version: '3'
services:
  manager-nginx:
    build:
      context: ./manager/docker
      dockerfile: nginx.docker
    volumes:
    - ./manager:/app
    depends_on:
    - manager-php-fpm
    ports:
    - "8080:80"
  manager-php-fpm:
    build:
      context: ./manager/docker
      dockerfile: php-fpm.docker
    volumes:
    - ./manager:/app
  manager-php-cli:
    build:
      context: ./manager/docker
      dockerfile: php-cli.docker
    volumes:
    - ./manager:/app
    - composer:/root/.composer/cache

volumes:
  composer: